"""report.py — assemble reports/results.md from artefacts (raw tables only).

ONE job: read the gate-passed JSON artefacts and emit reports/results.md as
machine-traceable tables (R3). This module writes NO prose, analysis, or
discussion — only the numbers produced by earlier stages. Every value here
traces to a file a marker can re-run.
"""
from __future__ import annotations
import json
from pathlib import Path

from .config import load_config, root

METRICS = ["accuracy", "precision", "recall", "f1", "roc_auc"]


def _fmt(x) -> str:
    if isinstance(x, bool):
        return "true" if x else "false"
    if isinstance(x, int):
        return str(x)
    if isinstance(x, float):
        return str(int(x)) if x.is_integer() else f"{x:.4f}"
    return str(x)


def _load(p: Path):
    return json.loads(p.read_text()) if p.exists() else None


def run() -> Path:
    cfg = load_config()
    eval_out = root() / cfg["evaluation"]["output"]
    comp = _load(eval_out / "comparison.json")
    base = _load(root() / cfg["baseline_output"] / "metrics.json")
    adv = _load(root() / cfg["advanced_output"] / "metrics.json")
    ext = _load(root() / cfg["external_validation"]["output"] / "external_metrics.json")
    card = _load(root() / cfg["data_generation"]["data_card"])

    lines: list[str] = []
    lines.append("# Results — raw tables\n")
    lines.append("> Auto-generated by `cvd.report` from gate-passed artefacts. "
                 "Numbers only; no interpretation (R1/R3).\n")

    if card:
        lines.append("## Dataset (Stage 01, synthetic)\n")
        lines.append("| field | value |")
        lines.append("|---|---|")
        for k in ["synthetic", "random_seed", "n_samples", "n_features",
                  "positive_prevalence_actual", "generator_version"]:
            if k in card:
                lines.append(f"| {k} | {_fmt(card[k])} |")
        lines.append("")

    # --- Comparison table: baseline vs advanced (held-out test) ---
    if comp:
        lines.append("## Baseline vs Advanced — held-out synthetic test\n")
        lines.append("| tier | model | " + " | ".join(METRICS) + " |")
        lines.append("|" + "---|" * (len(METRICS) + 2))
        for row in comp:
            cells = [_fmt(row.get(f"test_{m}")) for m in METRICS]
            lines.append(f"| {row['tier']} | {row['model']} | " + " | ".join(cells) + " |")
        lines.append("")
        lines.append(f"**Best model (by {cfg['evaluation']['select_best_by']}):** "
                     f"`{comp[0]['model']}` ({comp[0]['tier']}).\n")

    # --- Cross-validated train scores ---
    def _cv_block(title, group):
        if not group:
            return
        lines.append(f"## {title} — stratified {cfg['split']['cv_folds']}-fold CV (train)\n")
        lines.append("| model | " + " | ".join(METRICS) + " |")
        lines.append("|" + "---|" * (len(METRICS) + 1))
        for name, res in group.items():
            cells = [_fmt(res["cv"].get(m)) for m in METRICS]
            lines.append(f"| {name} | " + " | ".join(cells) + " |")
        lines.append("")

    _cv_block("Baseline", base)
    _cv_block("Advanced", adv)

    # --- Tuning results (advanced only) ---
    if adv and any("tuning" in r for r in adv.values()):
        lines.append("## Hyperparameter tuning (advanced models)\n")
        lines.append("| model | scoring | best CV score | best params |")
        lines.append("|---|---|---|---|")
        for name, res in adv.items():
            t = res.get("tuning")
            if t:
                lines.append(f"| {name} | {t['scoring']} | {_fmt(t['best_cv_score'])} "
                             f"| {t['best_params']} |")
        lines.append("")

    # --- Synthetic vs real gap (Stage 07) ---
    lines.append("## Synthetic vs Real — external validation (Stage 07)\n")
    if ext and ext.get("status") == "DONE":
        lines.append(f"Real dataset: **{ext['dataset']}**, "
                     f"n={ext['real_n_rows']}, "
                     f"positive prevalence={_fmt(ext['real_positive_prevalence'])}. "
                     f"Best model: `{ext['best_model']}`.\n")
        lines.append("| metric | synthetic test | real hold-out |")
        lines.append("|---|---|---|")
        for m in METRICS:
            lines.append(f"| {m} | {_fmt(ext['synthetic_test'][m])} "
                         f"| {_fmt(ext['real_holdout'][m])} |")
        lines.append("")
        lines.append(f"**ROC-AUC gap (synthetic − real): {_fmt(ext['roc_auc_gap'])}**\n")
        lines.append(f"Shared features ({len(ext['shared_features'])}): "
                     f"{', '.join(ext['shared_features'])}.\n")
        lines.append(f"Imputed features ({len(ext['imputed_features'])}): "
                     f"{', '.join(ext['imputed_features'])}.\n")
    elif ext:
        lines.append(f"Status: **{ext.get('status')}** — {ext.get('reason', '')}\n")
    else:
        lines.append("Stage 07 not run.\n")

    out_dir = root() / "reports"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "results.md"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[report] wrote {out_path}")
    return out_path


if __name__ == "__main__":
    run()
